version: '3.5'
services:
  order-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./order-service-main/
      args:
        serviceImageVersion: ${SERVICE_IMAGE_VERSION}
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    ports:
      - "8081:8080"
    depends_on:
      - order-service-mysql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://order-service-mysql/order_service
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
      EVENTUATE_TRAM_OUTBOX_PARTITIONING_OUTBOX_TABLES: ${EVENTUATE_OUTBOX_TABLES}
      EVENTUATE_DATABASE_SCHEMA: none

  customer-service:
    env_file:
      - ${ENV_FILE:-docker-compose-env-files/empty.env}
    build:
      context: ./customer-service-main/
      args:
        serviceImageVersion: ${SERVICE_IMAGE_VERSION}
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    ports:
      - "8082:8080"
    depends_on:
      - customer-service-mysql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://customer-service-mysql/customer_service
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
      EVENTUATE_TRAM_OUTBOX_PARTITIONING_OUTBOX_TABLES: ${EVENTUATE_OUTBOX_TABLES}
      EVENTUATE_DATABASE_SCHEMA: none

  api-gateway-service:
    build:
      context: ./api-gateway-service/
      args:
        serviceImageVersion: ${SERVICE_IMAGE_VERSION}
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION}
    ports:
      - "8083:8080"
    depends_on:
      - order-service
      - customer-service
    environment:
      ORDER_DESTINATIONS_ORDERSERVICEURL: http://order-service:8080
      CUSTOMER_DESTINATIONS_CUSTOMERSERVICEURL: http://customer-service:8080
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
      JAVA_OPTS: -Ddebug
      APIGATEWAY_TIMEOUT_MILLIS: ${APIGATEWAY_TIMEOUT_MILLIS:-1000}

  zookeeper:
    image: eventuateio/eventuate-zookeeper:${EVENTUATE_COMMON_VERSION?}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: -Xmx64m

  kafka:
    image: "eventuateio/eventuate-kafka:${EVENTUATE_MESSAGING_KAFKA_IMAGE_VERSION?}"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx192m

  customer-service-mysql:
    image: eventuateio/eventuate-vanilla-mysql8:${EVENTUATE_COMMON_VERSION?}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - EVENTUATE_OUTBOX_TABLES=${EVENTUATE_OUTBOX_TABLES}
      - MYSQL_DATABASE=customer_service

  order-service-mysql:
    image: eventuateio/eventuate-vanilla-mysql8:${EVENTUATE_COMMON_VERSION?}
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - EVENTUATE_OUTBOX_TABLES=${EVENTUATE_OUTBOX_TABLES}
      - MYSQL_DATABASE=order_service

  cdc-service:
    image: eventuateio/eventuate-cdc-service:${EVENTUATE_CDC_VERSION?}
    ports:
      - "8099:8080"
    depends_on:
      - customer-service-mysql
      - order-service-mysql
      - kafka
      - zookeeper
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

      EVENTUATE_CDC_READER_READER1_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:mysql://customer-service-mysql:3306/customer_service
      EVENTUATE_CDC_READER_READER1_MONITORINGSCHEMA: customer_service
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: root
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/customer_service
      EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTUNIQUEID: 1
      EVENTUATE_CDC_READER_READER1_OFFSETSTOREKEY: MySqlBinlogCustomerService
      EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME: db.history.common
      EVENTUATE_CDC_READER_READER1_OUTBOXID: 1

      EVENTUATE_CDC_READER_READER2_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:mysql://order-service-mysql:3306/order_service
      EVENTUATE_CDC_READER_READER2_MONITORINGSCHEMA: order_service
      EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: root
      EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/order_service
      EVENTUATE_CDC_READER_READER2_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER2_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER2_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER2_MYSQLBINLOGCLIENTUNIQUEID: 2
      EVENTUATE_CDC_READER_READER2_OFFSETSTOREKEY: MySqlBinlogOrderService
      EVENTUATE_CDC_READER_READER2_OFFSETSTORAGETOPICNAME: db.history.common
      EVENTUATE_CDC_READER_READER2_OUTBOXID: 2

      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA: customer_service

      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader2
      EVENTUATE_CDC_PIPELINE_PIPELINE2_EVENTUATEDATABASESCHEMA: order_service

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    environment:
      JAVA_OPTS: -Xmx64m
